codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 1%

ignore:
  - "**/*.g.dart"
  - "**/*.ease.dart"
  - "apps/**"
  - "packages/ease_annotation/**"
  - "**/test/**"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
