name: ease
repository: https://github.com/y3l1n4ung/ease

packages:
  - packages/*
  - apps/*

# ignore:
#   - '**/example'  # uncomment if you have example packages to exclude

command:
  version:
    linkToCommits: true
    workspaceChangelog: true

scripts:
  # Dependencies
  get:
    description: Get dependencies
    run: melos exec -- flutter pub get

  upgrade:
    description: Upgrade dependencies
    run: melos exec -- flutter pub upgrade

  # Code quality
  analyze:
    description: Analyze with fatal warnings
    run: melos exec -- dart analyze . --fatal-infos

  format:
    description: Format Dart files
    run: melos exec -- dart format .

  format:check:
    description: Check format (CI)
    run: melos exec -- dart format . --set-exit-if-changed -o none

  fix:
    description: Apply dart fix
    run: melos exec -- dart fix --apply

  # Testing
  test:all:
    description: Run all tests
    run: melos run test:dart && melos run test:flutter

  test:dart:
    description: Dart package tests
    run: melos exec --fail-fast -- dart test
    packageFilters:
      dirExists: test
      flutter: false

  test:flutter:
    description: Flutter package tests
    run: melos exec --fail-fast -- flutter test
    packageFilters:
      flutter: true
      dirExists: test

  test:coverage:
    description: Tests with coverage
    run: melos run test:coverage:flutter && melos run test:coverage:dart

  test:coverage:flutter:
    description: Flutter package tests with coverage
    run: melos exec --fail-fast --concurrency=1 -- flutter test --coverage
    packageFilters:
      flutter: true
      dirExists: test

  test:coverage:dart:
    description: Dart package tests with coverage
    run: |
      dart pub global activate coverage
      melos exec --fail-fast -- "dart pub global run coverage:test_with_coverage"
    packageFilters:
      flutter: false
      dirExists: test

  # Code generation
  generate:
    description: Run build_runner
    run: melos exec --order-dependents --fail-fast -- dart run build_runner build -d
    packageFilters:
      dependsOn: build_runner

  generate:watch:
    description: build_runner watch
    run: melos exec -- dart run build_runner watch -d
    packageFilters:
      dependsOn: build_runner

  # DevTools extension
  build:devtools:
    description: Build DevTools extension
    run: |
      cd packages/ease_devtools_extension && \
      flutter build web --release && \
      rm -rf extension/devtools/build && \
      cp -r build/web extension/devtools/build && \
      echo "DevTools extension built!"

  # Publishing
  publish:dart:
    description: Publish Dart packages
    run: melos exec -- dart pub publish
    packageFilters:
      flutter: false
      noPrivate: true

  publish:flutter:
    description: Publish Flutter packages
    run: melos exec -- flutter pub publish
    packageFilters:
      flutter: true
      noPrivate: true

  publish:dry:dart:
    description: Dry run publish Dart packages
    run: melos exec -- dart pub publish --dry-run
    packageFilters:
      flutter: false
      noPrivate: true

  publish:dry:flutter:
    description: Dry run publish Flutter packages
    run: melos exec -- flutter pub publish --dry-run
    packageFilters:
      flutter: true
      noPrivate: true


  # Maintenance
  clean:
    description: Clean Flutter packages
    run: melos exec -- flutter clean
    packageFilters:
      flutter: true

  # Setup
  setup:hooks:
    description: Install git hooks
    run: ./scripts/setup-hooks.sh
