builders:
  ease_builder:
    import: "package:ease_generator/ease_generator.dart"
    builder_factories: ["easeBuilder"]
    build_extensions: {".dart": [".ease.dart"]}
    auto_apply: dependents
    build_to: source
